<?php

namespace Database\Seeders;

use App\Models\MasterCustomerBranch;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MasterCustomerBranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '1','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '2','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '3','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '4','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '5','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '6','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '7','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '8','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '9','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '10','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '11','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '12','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '13','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '14','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '15','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '16','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '17','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '18','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '19','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '20','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '21','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '22','customer_branch' => 'Solo Baru']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '23','customer_branch' => 'Kartasura']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '24','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '25','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '26','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '27','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '28','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '29','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '30','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '31','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '32','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '33','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '34','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '35','customer_branch' => 'Depok RTM']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '35','customer_branch' => 'Pondok Indah']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '35','customer_branch' => 'Bandung']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '35','customer_branch' => 'Depok Kartini']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '35','customer_branch' => 'BSD']);
        MasterCustomerBranch::create(['outlet_id' => '0006','customer_id' => '35','customer_branch' => 'Tebet']);
        MasterCustomerBranch::create(['outlet_id' => '0007','customer_id' => '35','customer_branch' => 'Ciputat']);
        MasterCustomerBranch::create(['outlet_id' => '0008','customer_id' => '35','customer_branch' => 'Bekasi']);
        MasterCustomerBranch::create(['outlet_id' => '0009','customer_id' => '35','customer_branch' => 'Tanah Merdeka']);
        MasterCustomerBranch::create(['outlet_id' => '0010','customer_id' => '35','customer_branch' => 'Wastu Kencana']);
        MasterCustomerBranch::create(['outlet_id' => '0011','customer_id' => '35','customer_branch' => 'Kuningan']);
        MasterCustomerBranch::create(['outlet_id' => '0012','customer_id' => '35','customer_branch' => 'Ciledug']);
        MasterCustomerBranch::create(['outlet_id' => '0013','customer_id' => '35','customer_branch' => 'Palembang Sukamto']);
        MasterCustomerBranch::create(['outlet_id' => '0014','customer_id' => '35','customer_branch' => 'Bali Teuku Umar']);
        MasterCustomerBranch::create(['outlet_id' => '0015','customer_id' => '35','customer_branch' => 'Batam']);
        MasterCustomerBranch::create(['outlet_id' => '0016','customer_id' => '35','customer_branch' => 'Manado Piere Tendean']);
        MasterCustomerBranch::create(['outlet_id' => '0017','customer_id' => '35','customer_branch' => 'Semarang Jati Raya']);
        MasterCustomerBranch::create(['outlet_id' => '0018','customer_id' => '35','customer_branch' => 'Surabaya Mulyosari']);
        MasterCustomerBranch::create(['outlet_id' => '0019','customer_id' => '35','customer_branch' => 'Yogyakarta Cik di tiro']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '36','customer_branch' => 'MHJS/Jakarta Selatan']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '36','customer_branch' => 'MHTG/Tangerang']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '36','customer_branch' => 'MHKN/Kuningan']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '36','customer_branch' => 'MHSB/Surabaya']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '36','customer_branch' => 'MHBD /Bandung']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '37','customer_branch' => 'Solo']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '37','customer_branch' => 'Sragen']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '37','customer_branch' => 'Sukoharjo']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '37','customer_branch' => 'Purwodadi/Jogja']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '38','customer_branch' => 'Cipaku/Pusat']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '38','customer_branch' => 'Sam Marie Wijaya']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '38','customer_branch' => 'Sam Marie Basra']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '38','customer_branch' => 'Klinik Mutiara Batam']);
        MasterCustomerBranch::create(['outlet_id' => '0008','customer_id' => '38','customer_branch' => 'Cibubur']);
        MasterCustomerBranch::create(['outlet_id' => '0009','customer_id' => '38','customer_branch' => 'Klinik CMC Cikarang ']);
        MasterCustomerBranch::create(['outlet_id' => '0010','customer_id' => '38','customer_branch' => 'RSIA Evasari ']);
        MasterCustomerBranch::create(['outlet_id' => '0013','customer_id' => '38','customer_branch' => 'Bekasi ']);
        MasterCustomerBranch::create(['outlet_id' => '0014','customer_id' => '38','customer_branch' => 'Klinik Cikadu Tanjung Lesung']);
        MasterCustomerBranch::create(['outlet_id' => '0016','customer_id' => '38','customer_branch' => 'BSD ']);
        MasterCustomerBranch::create(['outlet_id' => '0017','customer_id' => '38','customer_branch' => 'Karawang']);
        MasterCustomerBranch::create(['outlet_id' => '0019','customer_id' => '38','customer_branch' => 'RSAB Tangerang ']);
        MasterCustomerBranch::create(['outlet_id' => '0020','customer_id' => '38','customer_branch' => 'Surabaya ']);
        MasterCustomerBranch::create(['outlet_id' => '0022','customer_id' => '38','customer_branch' => 'RSAB Bekasi Barat']);
        MasterCustomerBranch::create(['outlet_id' => '0023','customer_id' => '38','customer_branch' => 'WESTERINDO BEKASI TIMUR (LAB COVID)']);
        MasterCustomerBranch::create(['outlet_id' => '0021','customer_id' => '38','customer_branch' => 'LIS CLOUD']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '39','customer_branch' => 'KEDOYA']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '39','customer_branch' => 'CIUJUNG']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '39','customer_branch' => 'KELAPA GADING']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '39','customer_branch' => 'CITRA GARDEN']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '39','customer_branch' => 'BSD']);
        MasterCustomerBranch::create(['outlet_id' => '0006','customer_id' => '39','customer_branch' => 'TANGERANG']);
        MasterCustomerBranch::create(['outlet_id' => '0007','customer_id' => '39','customer_branch' => 'ANGKE']);
        MasterCustomerBranch::create(['outlet_id' => '0008','customer_id' => '39','customer_branch' => 'GADING SERPONG']);
        MasterCustomerBranch::create(['outlet_id' => '0009','customer_id' => '39','customer_branch' => 'SEMANAN']);
        MasterCustomerBranch::create(['outlet_id' => '0010','customer_id' => '39','customer_branch' => 'GANDARIA']);
        MasterCustomerBranch::create(['outlet_id' => '0011','customer_id' => '39','customer_branch' => 'MANGGA BESAR']);
        MasterCustomerBranch::create(['outlet_id' => '0012','customer_id' => '39','customer_branch' => 'DENPASAR']);
        MasterCustomerBranch::create(['outlet_id' => '0013','customer_id' => '39','customer_branch' => 'SUNTER']);
        MasterCustomerBranch::create(['outlet_id' => '0014','customer_id' => '39','customer_branch' => 'PURI INDAH']);
        MasterCustomerBranch::create(['outlet_id' => '0015','customer_id' => '39','customer_branch' => 'BEKASI']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '40','customer_branch' => 'ELLA SUPOMO/PUSAT']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '40','customer_branch' => 'ELLA KARTASURA']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '40','customer_branch' => 'ELLA JATEN']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '40','customer_branch' => 'ELLA PANJAITAN']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '40','customer_branch' => 'ELLA KLATEN']);
        MasterCustomerBranch::create(['outlet_id' => '0006','customer_id' => '40','customer_branch' => 'ELLA LAWEYAN']);
        MasterCustomerBranch::create(['outlet_id' => '0007','customer_id' => '40','customer_branch' => 'ELLA SRAGEN']);
        MasterCustomerBranch::create(['outlet_id' => '0008','customer_id' => '40','customer_branch' => 'ELLA WONOGIRI']);
        MasterCustomerBranch::create(['outlet_id' => '0009','customer_id' => '40','customer_branch' => 'ELLA MADIUN']);
        MasterCustomerBranch::create(['outlet_id' => '0010','customer_id' => '40','customer_branch' => 'ELLA JAKARTA BINTARO']);
        MasterCustomerBranch::create(['outlet_id' => '0011','customer_id' => '40','customer_branch' => 'ELLA SEMARANG KELUD']);
        MasterCustomerBranch::create(['outlet_id' => '0012','customer_id' => '40','customer_branch' => 'ELLA MAGELANG SUGIONO']);
        MasterCustomerBranch::create(['outlet_id' => '0013','customer_id' => '40','customer_branch' => 'ELLA KUDUS SUNAN']);
        MasterCustomerBranch::create(['outlet_id' => '0014','customer_id' => '40','customer_branch' => 'ELLA YOGYA GODEAN']);
        MasterCustomerBranch::create(['outlet_id' => '0015','customer_id' => '40','customer_branch' => 'ELLA PURWOKERTO OVERSTE']);
        MasterCustomerBranch::create(['outlet_id' => '0016','customer_id' => '40','customer_branch' => 'ELLA TEBET']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '40','customer_branch' => 'ELLA BEAUTY STORE']);
        MasterCustomerBranch::create(['outlet_id' => '0017','customer_id' => '40','customer_branch' => 'ELLA LAMPUNG']);
        MasterCustomerBranch::create(['outlet_id' => '0000','customer_id' => '40','customer_branch' => 'ELLA TRAINING']);
        MasterCustomerBranch::create(['outlet_id' => '0018','customer_id' => '40','customer_branch' => 'ELLA MALANG MERBABU']);
        MasterCustomerBranch::create(['outlet_id' => '0019','customer_id' => '40','customer_branch' => 'ELLA SIDOARJO']);
        MasterCustomerBranch::create(['outlet_id' => '0020','customer_id' => '40','customer_branch' => 'ELLA SALATIGA IMAM BONJOL']);
        MasterCustomerBranch::create(['outlet_id' => '1001','customer_id' => '40','customer_branch' => 'GLOWLABS SOLO SUPOMO']);
        MasterCustomerBranch::create(['outlet_id' => '0021','customer_id' => '40','customer_branch' => 'ELLA SURABAYA DHARMA HUSADA']);
        MasterCustomerBranch::create(['outlet_id' => '0022','customer_id' => '40','customer_branch' => 'ELLA MAGELANG 2']);
        MasterCustomerBranch::create(['outlet_id' => '0024','customer_id' => '40','customer_branch' => 'ELLA KEDIRI IMAM BONJOL']);
        MasterCustomerBranch::create(['outlet_id' => '0025','customer_id' => '40','customer_branch' => 'ELLA TEGAL KAPTEN ISMAIL']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '41','customer_branch' => 'KLINIK BONA MITRA KELUARGA BANDUNG']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '41','customer_branch' => 'BIC MENTENG']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '41','customer_branch' => 'LAB DIAGNOS MAKASSAR']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '41','customer_branch' => 'LAB DIAGNOS CIPUTAT']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '41','customer_branch' => 'LAB DIAGNOS DENPASAR']);
        MasterCustomerBranch::create(['outlet_id' => '0006','customer_id' => '41','customer_branch' => 'LAB DIAGNOS BATAM BANDARA']);
        MasterCustomerBranch::create(['outlet_id' => '0007','customer_id' => '41','customer_branch' => 'LAB DIAGNOS BATAM JASMINE']);
        MasterCustomerBranch::create(['outlet_id' => '0008','customer_id' => '41','customer_branch' => 'LAB DIAGNOS JAKARTA KIZUNA']);
        MasterCustomerBranch::create(['outlet_id' => '0009','customer_id' => '41','customer_branch' => 'LAB DIAGNOS DUMAI GRAHA YASMINE']);
        MasterCustomerBranch::create(['outlet_id' => '0010','customer_id' => '41','customer_branch' => 'LAB DIAGNOS DEPOK MARGONDA']);
        MasterCustomerBranch::create(['outlet_id' => '0011','customer_id' => '41','customer_branch' => 'LAB DIAGNOS PADANG PROKLAMASI']);
        MasterCustomerBranch::create(['outlet_id' => '0012','customer_id' => '41','customer_branch' => 'LAB DIAGNOS BALI KLUNGKUNG']);
        MasterCustomerBranch::create(['outlet_id' => '0013','customer_id' => '41','customer_branch' => 'RSIA-RSU MENTENG']);
        MasterCustomerBranch::create(['outlet_id' => '0014','customer_id' => '41','customer_branch' => 'LAB DIAGNOS BANDUNG PARAMARTA']);
        MasterCustomerBranch::create(['outlet_id' => '0015','customer_id' => '41','customer_branch' => 'LAB DIAGNOS PALEMBANG AZZAHRA']);
        MasterCustomerBranch::create(['outlet_id' => '0016','customer_id' => '41','customer_branch' => 'LAB DIAGNOS BATAM ABULYATAMA']);
        MasterCustomerBranch::create(['outlet_id' => '0017','customer_id' => '41','customer_branch' => 'LAB DIAGNOS DENPASAR BIC']);
        MasterCustomerBranch::create(['outlet_id' => '0018','customer_id' => '41','customer_branch' => 'LAB DIAGNOS JAKARTA GENOMIC']);
        MasterCustomerBranch::create(['outlet_id' => '0019','customer_id' => '41','customer_branch' => 'LAB DIAGNOS BREBES AMANAH MAHMUDAH']);
        MasterCustomerBranch::create(['outlet_id' => '0020','customer_id' => '41','customer_branch' => 'LAB DIAGNOS PEKANBARU BUDHI MULIA']);
        MasterCustomerBranch::create(['outlet_id' => '9001','customer_id' => '41','customer_branch' => 'LAB DIAGNOS PUSAT']);
        MasterCustomerBranch::create(['outlet_id' => '9999','customer_id' => '41','customer_branch' => 'TRAINING']);
        MasterCustomerBranch::create(['outlet_id' => '0021','customer_id' => '41','customer_branch' => 'BIC BANDUNG']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '42','customer_branch' => 'Jakarta']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '42','customer_branch' => 'Bandung']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '42','customer_branch' => 'Makassar']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '42','customer_branch' => 'Surabaya']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '42','customer_branch' => 'Medan']);
        MasterCustomerBranch::create(['outlet_id' => '0001','customer_id' => '43','customer_branch' => 'Jakarta Ciputat']);
        MasterCustomerBranch::create(['outlet_id' => '0002','customer_id' => '43','customer_branch' => 'Bandung Merdeka']);
        MasterCustomerBranch::create(['outlet_id' => '0003','customer_id' => '43','customer_branch' => 'Semarang Sultan Agung']);
        MasterCustomerBranch::create(['outlet_id' => '0004','customer_id' => '43','customer_branch' => 'Denpasar Puputan']);
        MasterCustomerBranch::create(['outlet_id' => '0005','customer_id' => '43','customer_branch' => 'Karawang']);
        MasterCustomerBranch::create(['outlet_id' => '0006','customer_id' => '43','customer_branch' => 'Yogyakarta']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '44','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '45','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '46','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '47','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '48','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '49','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '50','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '51','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '52','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '53','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '54','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '55','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '56','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '57','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '58','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '59','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '60','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '61','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '62','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '63','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '64','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '65','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '66','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '67','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '68','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '69','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '70','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '71','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '72','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '73','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '74','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '75','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '76','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '77','customer_branch' => '']);
        MasterCustomerBranch::create(['outlet_id' => '','customer_id' => '78','customer_branch' => '']);
    }
}
